server.port: 8003


# Actuator Endpoint Configurations
info: # /actuator/info
  app:
    name: ${spring.application.name}

management:
  metrics:
    tags:
      service: ${spring.application.name} # Additional, custom tag to allow filtering by service (instance)
    export:
      influx:
        auto-create-db: true
        db: spring-boot-metrics
        uri: http://localhost:8086
        step: 20s
        user-name: admin
        password: admin
  endpoints:
    web:
      exposure:
        include:
        - "*"

spring:
  application:
    name: ServiceC
  sleuth:
    propagation:
      type: W3C
    otel:
      config:
        traceIdRatioBased: 1.0